import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import './styles/tokens.css'
import './style.css'
import './portal.css'
import './theme.css'
import './refinement.css'
import './admin.css'
import './presets.css'
import './styles/motion.css'
import './styles/ui.css'
import './styles/admin-flows.css'
import './styles/experience.css'
import './styles/home-apple.css'

createApp(App).use(router).mount('#app')
